# Generated by Django 2.2 on 2020-07-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('RUT', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('comuna', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_final', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('cliente', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='provedor',
            fields=[
                ('RUT', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=11)),
                ('nombre', models.CharField(max_length=50)),
                ('web', models.CharField(max_length=500)),
                ('direccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.direccion')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('categoria', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.categoria')),
                ('provedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.provedor')),
                ('venta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aplicacion.venta')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.direccion'),
        ),
    ]
